#!/bin/bash -i

# If we're using conda python
if [ "$CONDA_PREFIX" != "" ]; then
    # NOTE: The KRO environment is created with:
    #       conda env create -f environment.yaml
    CONDA_BASE=$(conda info --base)
    echo "Found CONDA_BASE=$CONDA_BASE"
    source $CONDA_BASE/etc/profile.d/conda.sh

    #get script dir (so we know full path to keck_vnc_launcher.py)
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
    echo "Found DIR=$DIR"

    # Launch the script
    if [ -e $CONDA_BASE/envs/KRO/bin/python3 ]; then
        echo "Launching using conda KRO environment"
        conda activate KRO
        $CONDA_BASE/envs/KRO/bin/python3 $DIR/keck_vnc_launcher.py -c $DIR/local_config.yaml $@
    else
        echo "Launching using conda current environment"
        $CONDA_BASE/bin/python3 $DIR/keck_vnc_launcher.py -c $DIR/local_config.yaml $@
    fi
else
    echo "We are unable to determine the correct python version to run the"
    echo "Remote Observing software.  We will now try a generic python3 call,"
    echo "if this fails, simply execute the keck_vnc_launcher.py file using the"
    echo "correct python version for your system and use the same arguments you"
    echo "would use with the start_keck_viewers script.  For example:"
    echo "  /path/to/python3 keck_vnc_launcher.py numbered_account"
    echo "Of course, you should use the proper path to your python executable"
    echo "and the correct numbered account."

    # just try whatever is in the path and hope it works
    python3 keck_vnc_launcher.py $@
fi
