#!/bin/bash

# If we're using conda python
if [ "$CONDA_PREFIX" != "" ]; then
    # activate conda environment
    # NOTE: The KRO environment is created with:
    #       conda env create -f environment.yaml
    source $CONDA_PREFIX/etc/profile.d/conda.sh
    conda activate KRO

    #change to script dir (so we don't need full path to keck_vnc_launcher.py)
    DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
    cd $DIR

    # Launch the script
    if [ -e $CONDA_PREFIX/envs/KRO/bin/python3 ]; then
        # Launch using conda KRO environment
        $CONDA_PREFIX/envs/KRO/bin/python3 keck_vnc_launcher.py $@
    else
        # Try launching via conda base environment
        $CONDA_PREFIX/bin/python3 keck_vnc_launcher.py $@
    fi
else
    echo "We are unable to determine the correct python version to run the"
    echo "Remote Observing software.  We will now try a generic python3 call,"
    echo "if this fails, simply execute the keck_vnc_launcher.py file using the"
    echo "correct python version for your system and use the same arguments you"
    echo "would use with the start_keck_viewers script.  For example:"
    echo "  /path/to/python3 keck_vnc_launcher.py numbered_account"
    echo "Of coure, you should use the proper path to your python executable"
    echo "and the correct numbered account."

    # just try whatever is in the path and hope it works
    python3 keck_vnc_launcher.py $@
fi
